language: csharp
solution: DarkMultiPlayer.sln

env:
  global:
  - KSP_VERSION="1.2.2"

before_script:
- chmod +x .ci/before_script.sh && ./.ci/before_script.sh

script:
- xbuild /p:Configuration=Release $TRAVIS_SOLUTION